# Generated by Django 5.0 on 2023-12-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('digitalwatch', 'digitalwatch'), ('analogwatch', 'analogwatch')], default='digitalwatch', max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ecom',
        ),
    ]
